ROOT_PATH: "/Backup/print20"
HOST: "http://123d.makerlover.cn"

ALI_GATEWAY: "https://mapi.alipay.com/gateway.do"
ALI_KEY: "cujt7hpauxnv6blgcr9tlh32fq1rrapk"
ALI_ID: "2088002569686604"




#1845*1845, 156mm * 156mm

cover_width_6: <%= 6.142*72 %>
cover_height_6: <%= 6.142*72 %>

#(3+20)mm
cover_margin: <%= 0.906*72 %>

#17mm
cover_strip_width_A:   <%= 0.669*72 %>
#20mm
cover_strip_width_B:   <%= 0.787*72 %>
#23mm
cover_strip_width_C:   <%= 0.906*72 %>

#106 * 77 
photo_card_width: <%= 3.031*72 %>
photo_card_height: <%= 4.173*72 %>
#margin 3mm
photo_card_margin: <%= 0.118*72 %>





image_file_suffix: ".jpg"
